_target_: pipeline.mat_invent.MatInvent

rl_epoch: ${rl_epoch}
device: ${device}
save_dir: ./
save_freq: 100
sample_cfg: ${sample_cfg}
topk_ratio: 0.5

replay: True
replay_args:
  buffer_size: 100
  sample_size: 10
  reward_cutoff: 0.1
  priority_beta: 0.0

div_filter: True
df_args:
  tol: 3
  buff: 6

finetune_cfg:
  batch_size: ${eval_size}
  accum_steps: 50
  epochs: 3
  sigma: 0.025
  num_sampled_timesteps: 50
  ema_decay: 0.0
  target_kl: 999
  sigma_lr: 0.0
  residual_alpha_init: 1.0
  residual_warmup_steps: 1
